### PR TITLE
Functions for calculating 'matching ratio' based on Ascii values

### PR DESCRIPTION
**Pull request by rishirajsurti**
Added functions to compare strings based on Ascii values and relative position of characters.

### CODE REVIEW

**Comment by josegonzalez** [comment]
Needs tests and pep8 compliance.

**Comment by rishirajsurti** [comment]
Thanks for pointing out. Resolved.

**Comment by josegonzalez** [comment]
Still needs tests. Also documentation on the readme, as well as guidance on when this might be more useful than the existing methods.

**Comment by zackkitzmiller** [comment]
@acslater00 might want to weight in on this one as well.

**Pull request closed without merging**
