### PR TITLE
Move extract test methods into the process test.

### PR DESCRIPTION
**Pull request by shalecraig**
Somehow, they ended up in the `RatioTest`, despite asserting that the `ProcessTest` works.

### CODE REVIEW

**Comment by josegonzalez** [comment]
Mind also moving the `setup` method up as well?

**Comment by shalecraig** [comment]
done! Please let me know if you want me to rebase/squash.

**Comment by josegonzalez** [comment]
Please squash/rebase and I will merge after :)

**Comment by josegonzalez** [comment]
:bump:

**Comment by shalecraig** [comment]
Updated

**Pull request merged**
